parameters:
    tables.boardnotices.notices: %core.table_prefix%notices
    tables.boardnotices.notices_rules: %core.table_prefix%notices_rules

services:
    fq.boardnotices.datalayer:
        class: fq\boardnotices\datalayer
        arguments:
            - @dbal.conn
            - @user
            - %tables.boardnotices.notices%
            - %tables.boardnotices.notices_rules%

    fq.boardnotices.listener:
        class: fq\boardnotices\event\listener
        arguments:
            - @user
            - @template
        tags:
            - { name: event.listener }

    fq.boardnotices.rules.birthday:
        class: fq\boardnotices\rules\birthday
        arguments:
            - @user

    fq.boardnotices.rules.in_default_usergroup:
        class: fq\boardnotices\rules\in_default_usergroup
        arguments:
            - @user

    fq.boardnotices.rules.in_usergroup:
        class: fq\boardnotices\rules\in_usergroup
        arguments:
            - @user

    fq.boardnotices.rules.has_never_posted:
        class: fq\boardnotices\rules\has_never_posted
        arguments:
            - @user

    fq.boardnotices.rules.style:
        class: fq\boardnotices\rules\style
        arguments:
            - @user
