sudo: required
language: php
matrix:
  include:
  - php: 5.4
    env: DB=postgres
  - php: 5.4
    env: DB=sqlite3
  - php: 5.4
    env: DB=mysqli
  - php: 5.5
    env: DB=mysqli
  - php: 5.6
    env: DB=mysqli
  - php: 7.0
    env: DB=mysqli
  - php: 7.1
    env: DB=mysqli
  - php: 7.2
    env: DB=mysqli
  - php: hhvm
    env: DB=mysqli
  allow_failures:
  - php: hhvm
  fast_finish: true
env:
  global:
  - EXTNAME="fq/boardnotices"
  - SNIFF="1"
  - IMAGE_ICC="0"
  - EPV="0"
  - PHPBB_BRANCH="3.2.x"
  - secure: PD3tE5WsYvoOZE08hyFCSsrfVFWf0fNslPdjBAkI7yhjQjQIXNkfE+Apr5iqDdqe87FVR9j5WuZ8YLEXc4Q6iW6Rdh33eQY7CbXsupaK37rhuCqwGeNv1vts73XlvP3q680vm33UdBFO7A4yd48BDBT3s9ynvpt87yfI9sfWKAKNdVDAhXxv+XSB9UXXJwASn3wjQ1V5W5MIBZhLRCMpgcZANEu/0UPrKhAtdzqa8nxIXjty8tIhEOUogKkgCVH6FvvrQFbvWrMwMcJVoUWyJXVnRWywFDuk65XdkN4DkRd34NRW20ZTAE94VfVraNxkN3regt6GMPcxmMSBPDA5Gdn9rhFpHmhJbpVSXI31+cFObPvGreiBo3rHIwOs0yFarELwYh+gTcweb2kC3atbVkXZczCPaRI2cWsZz7kkpA9b1W3/miirBFbmTfOIKS7+OTIipR+XETrEJGeUuOaSY9fTwloSQNokOIkRHniU5G/lf3bvclPsDCRVmUtDlOjbq7f6gXejIOekz4slfq4u/fQUIfE+n3OR3eEaz2SdRHLDtyRTT+NoqnEQ98JZqzgMudVHslaFtQ9Hy6zLTXHbcV4BwywAcE5oMMFicPy75/ukCu41xHP1cVpyiNHPoysry6n16qnd/Ezupylw9ZkBYF7A2vjPl3K16gDvAU6FPA4=
branches:
  only:
  - master
  - /^(3\.[1-9]|[4-9]\.\d)\.x$/
install:
- phpenv versions
- composer install --dev --no-interaction --prefer-source
- travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
- cd ../../phpBB3
- travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
- travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION
before_script:
- travis/setup-database.sh $DB $TRAVIS_PHP_VERSION
script:
- sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION
  $EXTNAME; fi"
- sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION;
  fi"
- phpBB/vendor/bin/phpunit --configuration phpBB/ext/$EXTNAME/travis/phpunit-$DB-travis.xml
  --bootstrap ./tests/bootstrap.php
- sh -c "if [ '$EPV' != '0' ] && [ '$TRAVIS_PHP_VERSION' = '5.3.3' ] && [ '$DB' =
  'mysqli' ]; then phpBB/ext/$EXTNAME/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/';
  fi"
