parameters:
    tables.boardnotices.notices: %core.table_prefix%notices
    tables.boardnotices.notices_rules: %core.table_prefix%notices_rules

services:
    fq.boardnotices.datalayer:
        class: fq\boardnotices\datalayer
        arguments:
            - @dbal.conn
            - @user
            - @cache
            - @config
            - %tables.boardnotices.notices%
            - %tables.boardnotices.notices_rules%

    fq.boardnotices.listener:
        class: fq\boardnotices\event\listener
        arguments:
            - @user
            - @template
        tags:
            - { name: event.listener }

    fq.boardnotices.domain.rules:
        class: fq\boardnotices\domain\rules
        arguments:
            - %core.root_path%

    fq.boardnotices.rules.birthday:
        class: fq\boardnotices\rules\birthday
        arguments:
            - @user

    fq.boardnotices.rules.in_default_usergroup:
        class: fq\boardnotices\rules\in_default_usergroup
        arguments:
            - @user
            - @fq.boardnotices.datalayer

    fq.boardnotices.rules.in_usergroup:
        class: fq\boardnotices\rules\in_usergroup
        arguments:
            - @user
            - @fq.boardnotices.datalayer

    fq.boardnotices.rules.has_never_posted:
        class: fq\boardnotices\rules\has_never_posted
        arguments:
            - @user
            - @fq.boardnotices.datalayer

    fq.boardnotices.rules.not_logged_in:
        class: fq\boardnotices\rules\not_logged_in
        arguments:
            - @user

    fq.boardnotices.rules.style:
        class: fq\boardnotices\rules\style
        arguments:
            - @user
            - @fq.boardnotices.datalayer

    fq.boardnotices.rules.language:
        class: fq\boardnotices\rules\language
        arguments:
            - @user
            - @fq.boardnotices.datalayer

    fq.boardnotices.rules.rank:
        class: fq\boardnotices\rules\rank
        arguments:
            - @user
            - @fq.boardnotices.datalayer

    fq.boardnotices.rules.in_forum:
        class: fq\boardnotices\rules\in_forum
        arguments:
            - @user
            - @request
